language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.10"
install: "/bin/true"
branches:
  only:
    - fix_broken_test_munin_master_node
before_install:
 - "cpanm --notest File::Copy::Recursive"
 - "cpanm --notest File::Slurp"
 - "cpanm --notest HTML::Template"
 - "cpanm --notest IO::Scalar"
 - "cpanm --notest IO::Socket::INET6"
 - "cpanm --notest Log::Log4perl"
 - "cpanm --notest Module::Build"
 - "cpanm --notest Module::Build"
 - "cpanm --notest Net::SNMP"
 - "cpanm --notest Net::SSLeay"
 - "cpanm --notest Test::Deep"
 - "cpanm --notest Test::Differences"
 - "cpanm --notest Test::LongString"
 - "cpanm --notest Test::MockModule"
 - "cpanm --notest Test::MockObject::Extends"
 - "cpanm --notest Time::HiRes"
